### PR TITLE
Kotlin 2.0.20

### LINKED ISSUE #9: Kotlin 2.0.20
Kotlin `2.0.20-Beta1` seems to introduce multiple breaking changes that seems trivial to fix. However, fixing them in a backward compatible way might not be possible.

### PR DESCRIPTION
**Pull request by lupuuss**
Closes #9

### CODE REVIEW

**Comment by makesappy** [comment]
Hi @lupuuss !
how hard is it for you to build remote kind of `2.1.1-K2.0.20-RC` version of this?

**Comment by lupuuss** [comment]
Hi @makesappy! I'm currently working on the next release, `2.2.0`, which should be completed this week. After that, I’ll have some time to release a snapshot version with Kotlin `2.0.20-RC`.

Could you share your specific use case for Kotlin `2.0.20-RC`? Perhaps I can assist you in another way until snapshot is released.

**Comment by makesappy** [comment]
Thanks for answering @lupuuss !
`2.2.0` still won't support kotlin `2.0.20-RC` ? 
My specific UC is that after migration my project to Kotlin 2.0.0 i've faced a specific issue that kotlin 2.0.0 was failing on during compilation of native sources (https://youtrack.jetbrains.com/issue/KT-68553/) .So , it was fixed by jetbrains' team in version `2.0.20-Beta2` which your library doesn't support yet 😄 . So to finish my migration - i need to wait for new release of your library since using kotlin `2.0.20-RC` is ok for me 🤷  
I know that anyway you will release library when kotlin `2.0.20` will be release as stable, and i can wait, but i thought if it is for you only about calling 1 gradle task for publishing it to remote - it will be possible. Up on you anyway, in case you will decide to release it with stable - i will patiently wait 👌

**Comment by lupuuss** [comment]
`2.2.0` will be based on Kotlin `2.0.10`. 
I understand you problem. After `2.2.0` I should be able to release a snapshot version with Kotlin  `2.0.20-RC` support for you.

**Comment by makesappy** [comment]
Hey, @lupuuss !
Is there a possibility to release it this week? :)
Thx beforehand 🙏

**Comment by lupuuss** [comment]
Hi! Yes, yes I remember. I tried to release it recently but had some issues with publishing process. I will try to publish it again today. If I fail today you should expect the release at the end of this week.

**Comment by lupuuss** [comment]
Hi @makesappy! I've released a `2.3.0-SNAPSHOT` with Kotlin `2.0.20-RC2` for you! 
You need 2 snapshot repositories (for both plugin dependencies and regular ones):
```kotlin
 // for Mokkery
maven { url = uri("https://s01.oss.sonatype.org/content/repositories/snapshots/") }

// for Poko annotations snapshot version that Mokkery depends on
maven { url = uri("https://oss.sonatype.org/content/repositories/snapshots/")  }
```

**Comment by makesappy** [comment]
Dear @lupuuss thank you very much 🙏  for you help with this, have a pleasant weekend!

**Comment by KitsuneAlex** [comment]
Thanking you as well for your quick fix! This broke our testsuite at work today :D

**Pull request merged**
