### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hashir1296**
Added code snippet to demonstrate how we can use Mokkery with Dependency injection such as Koin.

### CODE REVIEW

**Comment by lupuuss** [comment]
Hi! Could you clarify why this snippet should be in README? It does not seem like Mokkery specific and it mostly describes how to work with Koin in tests.

**Comment by hashir1296** [comment]
Hi Damian,

Thankyou for getting in touch. While your point is valid here is what i
think:

Think of this as "People like me are searching over the web about how we
can use DI + Mocking in KMP"

So the options are few and Mokkery is one of them.

1. Majority of the people using Mokkery will most probably be using a DI as
well. And incase of KMP its most likely to be Koin. Koin docs mention to
use a MockProvider and declareMock function to mock.
2. This snippet will speak out loud that we don't need to have a
MockProvider incase of Mokkery and can use mocks as straight forward as it
is.

If you still think this isn't the right platform, i can move this snippet
to koin's readme

Thanks!

**Comment by lupuuss** [comment]
I have no experience with `MockProvider`, and I don't really use Koin in tests, so correct me if I am wrong. As far as I understand, the documentation mentions `MockProvider` as a simplification for the boilerplate that comes with creating modules in tests. However, it doesn't seem to be mandatory. The sample you have provided should be true for injecting any objects in test - not only mocks. Also I am not sure how other mocking libraries for KMP interact with Koin. Is there anything that disqualifies them from using approach from your sample?

**Comment by lupuuss** [comment]
I'm closing this MR because it is inactive and conflicting (README.md content was migrated to the website).

**Pull request closed without merging**
